/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedKnowledgeVaultRouteImport } from './routes/_authenticated/knowledge-vault'
import { Route as AuthenticatedFreshdeskTicketsRouteImport } from './routes/_authenticated/freshdesk-tickets'
import { Route as AuthenticatedFreshdeskIntelligenceRouteImport } from './routes/_authenticated/freshdesk-intelligence'
import { Route as AuthenticatedContactDispatchRouteImport } from './routes/_authenticated/contact-dispatch'
import { Route as AuthenticatedConstellationsRouteImport } from './routes/_authenticated/constellations'
import { Route as AuthenticatedCompletedWorkRouteImport } from './routes/_authenticated/completed-work'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAssignedToMeRouteImport } from './routes/_authenticated/assigned-to-me'
import { Route as AuthenticatedAdditionalWorkRouteImport } from './routes/_authenticated/additional-work'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdditionalWorkIndexRouteImport } from './routes/_authenticated/additional-work.index'
import { Route as AuthenticatedContactDispatchArchiveRouteImport } from './routes/_authenticated/contact-dispatch.archive'
import { Route as AuthenticatedAccountsAccountNumberRouteImport } from './routes/_authenticated/accounts.$accountNumber'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedFreshdeskTicketsTicketIdWorkRouteImport } from './routes/_authenticated/freshdesk-tickets.$ticketId.work'
import { Route as AuthenticatedContactDispatchSessionIdWorkRouteImport } from './routes/_authenticated/contact-dispatch.$sessionId.work'
import { Route as AuthenticatedAdditionalWorkWorkIdWorkRouteImport } from './routes/_authenticated/additional-work.$workId.work'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeVaultRoute =
  AuthenticatedKnowledgeVaultRouteImport.update({
    id: '/knowledge-vault',
    path: '/knowledge-vault',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreshdeskTicketsRoute =
  AuthenticatedFreshdeskTicketsRouteImport.update({
    id: '/freshdesk-tickets',
    path: '/freshdesk-tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreshdeskIntelligenceRoute =
  AuthenticatedFreshdeskIntelligenceRouteImport.update({
    id: '/freshdesk-intelligence',
    path: '/freshdesk-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactDispatchRoute =
  AuthenticatedContactDispatchRouteImport.update({
    id: '/contact-dispatch',
    path: '/contact-dispatch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConstellationsRoute =
  AuthenticatedConstellationsRouteImport.update({
    id: '/constellations',
    path: '/constellations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompletedWorkRoute =
  AuthenticatedCompletedWorkRouteImport.update({
    id: '/completed-work',
    path: '/completed-work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignedToMeRoute =
  AuthenticatedAssignedToMeRouteImport.update({
    id: '/assigned-to-me',
    path: '/assigned-to-me',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdditionalWorkRoute =
  AuthenticatedAdditionalWorkRouteImport.update({
    id: '/additional-work',
    path: '/additional-work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdditionalWorkIndexRoute =
  AuthenticatedAdditionalWorkIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdditionalWorkRoute,
  } as any)
const AuthenticatedContactDispatchArchiveRoute =
  AuthenticatedContactDispatchArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedContactDispatchRoute,
  } as any)
const AuthenticatedAccountsAccountNumberRoute =
  AuthenticatedAccountsAccountNumberRouteImport.update({
    id: '/$accountNumber',
    path: '/$accountNumber',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFreshdeskTicketsTicketIdWorkRoute =
  AuthenticatedFreshdeskTicketsTicketIdWorkRouteImport.update({
    id: '/$ticketId/work',
    path: '/$ticketId/work',
    getParentRoute: () => AuthenticatedFreshdeskTicketsRoute,
  } as any)
const AuthenticatedContactDispatchSessionIdWorkRoute =
  AuthenticatedContactDispatchSessionIdWorkRouteImport.update({
    id: '/$sessionId/work',
    path: '/$sessionId/work',
    getParentRoute: () => AuthenticatedContactDispatchRoute,
  } as any)
const AuthenticatedAdditionalWorkWorkIdWorkRoute =
  AuthenticatedAdditionalWorkWorkIdWorkRouteImport.update({
    id: '/$workId/work',
    path: '/$workId/work',
    getParentRoute: () => AuthenticatedAdditionalWorkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/additional-work': typeof AuthenticatedAdditionalWorkRouteWithChildren
  '/assigned-to-me': typeof AuthenticatedAssignedToMeRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/completed-work': typeof AuthenticatedCompletedWorkRoute
  '/constellations': typeof AuthenticatedConstellationsRoute
  '/contact-dispatch': typeof AuthenticatedContactDispatchRouteWithChildren
  '/freshdesk-intelligence': typeof AuthenticatedFreshdeskIntelligenceRoute
  '/freshdesk-tickets': typeof AuthenticatedFreshdeskTicketsRouteWithChildren
  '/knowledge-vault': typeof AuthenticatedKnowledgeVaultRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/accounts/$accountNumber': typeof AuthenticatedAccountsAccountNumberRoute
  '/contact-dispatch/archive': typeof AuthenticatedContactDispatchArchiveRoute
  '/additional-work/': typeof AuthenticatedAdditionalWorkIndexRoute
  '/additional-work/$workId/work': typeof AuthenticatedAdditionalWorkWorkIdWorkRoute
  '/contact-dispatch/$sessionId/work': typeof AuthenticatedContactDispatchSessionIdWorkRoute
  '/freshdesk-tickets/$ticketId/work': typeof AuthenticatedFreshdeskTicketsTicketIdWorkRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/assigned-to-me': typeof AuthenticatedAssignedToMeRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/completed-work': typeof AuthenticatedCompletedWorkRoute
  '/constellations': typeof AuthenticatedConstellationsRoute
  '/contact-dispatch': typeof AuthenticatedContactDispatchRouteWithChildren
  '/freshdesk-intelligence': typeof AuthenticatedFreshdeskIntelligenceRoute
  '/freshdesk-tickets': typeof AuthenticatedFreshdeskTicketsRouteWithChildren
  '/knowledge-vault': typeof AuthenticatedKnowledgeVaultRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/accounts/$accountNumber': typeof AuthenticatedAccountsAccountNumberRoute
  '/contact-dispatch/archive': typeof AuthenticatedContactDispatchArchiveRoute
  '/additional-work': typeof AuthenticatedAdditionalWorkIndexRoute
  '/additional-work/$workId/work': typeof AuthenticatedAdditionalWorkWorkIdWorkRoute
  '/contact-dispatch/$sessionId/work': typeof AuthenticatedContactDispatchSessionIdWorkRoute
  '/freshdesk-tickets/$ticketId/work': typeof AuthenticatedFreshdeskTicketsTicketIdWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/_authenticated/additional-work': typeof AuthenticatedAdditionalWorkRouteWithChildren
  '/_authenticated/assigned-to-me': typeof AuthenticatedAssignedToMeRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/completed-work': typeof AuthenticatedCompletedWorkRoute
  '/_authenticated/constellations': typeof AuthenticatedConstellationsRoute
  '/_authenticated/contact-dispatch': typeof AuthenticatedContactDispatchRouteWithChildren
  '/_authenticated/freshdesk-intelligence': typeof AuthenticatedFreshdeskIntelligenceRoute
  '/_authenticated/freshdesk-tickets': typeof AuthenticatedFreshdeskTicketsRouteWithChildren
  '/_authenticated/knowledge-vault': typeof AuthenticatedKnowledgeVaultRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/accounts/$accountNumber': typeof AuthenticatedAccountsAccountNumberRoute
  '/_authenticated/contact-dispatch/archive': typeof AuthenticatedContactDispatchArchiveRoute
  '/_authenticated/additional-work/': typeof AuthenticatedAdditionalWorkIndexRoute
  '/_authenticated/additional-work/$workId/work': typeof AuthenticatedAdditionalWorkWorkIdWorkRoute
  '/_authenticated/contact-dispatch/$sessionId/work': typeof AuthenticatedContactDispatchSessionIdWorkRoute
  '/_authenticated/freshdesk-tickets/$ticketId/work': typeof AuthenticatedFreshdeskTicketsTicketIdWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/additional-work'
    | '/assigned-to-me'
    | '/audit-log'
    | '/completed-work'
    | '/constellations'
    | '/contact-dispatch'
    | '/freshdesk-intelligence'
    | '/freshdesk-tickets'
    | '/knowledge-vault'
    | '/reports'
    | '/settings'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/accounts/$accountNumber'
    | '/contact-dispatch/archive'
    | '/additional-work/'
    | '/additional-work/$workId/work'
    | '/contact-dispatch/$sessionId/work'
    | '/freshdesk-tickets/$ticketId/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/assigned-to-me'
    | '/audit-log'
    | '/completed-work'
    | '/constellations'
    | '/contact-dispatch'
    | '/freshdesk-intelligence'
    | '/freshdesk-tickets'
    | '/knowledge-vault'
    | '/reports'
    | '/settings'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/accounts/$accountNumber'
    | '/contact-dispatch/archive'
    | '/additional-work'
    | '/additional-work/$workId/work'
    | '/contact-dispatch/$sessionId/work'
    | '/freshdesk-tickets/$ticketId/work'
  id:
    | '__root__'
    | '/_authenticated'
    | '/access-denied'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/accounts'
    | '/_authenticated/additional-work'
    | '/_authenticated/assigned-to-me'
    | '/_authenticated/audit-log'
    | '/_authenticated/completed-work'
    | '/_authenticated/constellations'
    | '/_authenticated/contact-dispatch'
    | '/_authenticated/freshdesk-intelligence'
    | '/_authenticated/freshdesk-tickets'
    | '/_authenticated/knowledge-vault'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/accounts/$accountNumber'
    | '/_authenticated/contact-dispatch/archive'
    | '/_authenticated/additional-work/'
    | '/_authenticated/additional-work/$workId/work'
    | '/_authenticated/contact-dispatch/$sessionId/work'
    | '/_authenticated/freshdesk-tickets/$ticketId/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-vault': {
      id: '/_authenticated/knowledge-vault'
      path: '/knowledge-vault'
      fullPath: '/knowledge-vault'
      preLoaderRoute: typeof AuthenticatedKnowledgeVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freshdesk-tickets': {
      id: '/_authenticated/freshdesk-tickets'
      path: '/freshdesk-tickets'
      fullPath: '/freshdesk-tickets'
      preLoaderRoute: typeof AuthenticatedFreshdeskTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freshdesk-intelligence': {
      id: '/_authenticated/freshdesk-intelligence'
      path: '/freshdesk-intelligence'
      fullPath: '/freshdesk-intelligence'
      preLoaderRoute: typeof AuthenticatedFreshdeskIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact-dispatch': {
      id: '/_authenticated/contact-dispatch'
      path: '/contact-dispatch'
      fullPath: '/contact-dispatch'
      preLoaderRoute: typeof AuthenticatedContactDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/constellations': {
      id: '/_authenticated/constellations'
      path: '/constellations'
      fullPath: '/constellations'
      preLoaderRoute: typeof AuthenticatedConstellationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/completed-work': {
      id: '/_authenticated/completed-work'
      path: '/completed-work'
      fullPath: '/completed-work'
      preLoaderRoute: typeof AuthenticatedCompletedWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assigned-to-me': {
      id: '/_authenticated/assigned-to-me'
      path: '/assigned-to-me'
      fullPath: '/assigned-to-me'
      preLoaderRoute: typeof AuthenticatedAssignedToMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/additional-work': {
      id: '/_authenticated/additional-work'
      path: '/additional-work'
      fullPath: '/additional-work'
      preLoaderRoute: typeof AuthenticatedAdditionalWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/additional-work/': {
      id: '/_authenticated/additional-work/'
      path: '/'
      fullPath: '/additional-work/'
      preLoaderRoute: typeof AuthenticatedAdditionalWorkIndexRouteImport
      parentRoute: typeof AuthenticatedAdditionalWorkRoute
    }
    '/_authenticated/contact-dispatch/archive': {
      id: '/_authenticated/contact-dispatch/archive'
      path: '/archive'
      fullPath: '/contact-dispatch/archive'
      preLoaderRoute: typeof AuthenticatedContactDispatchArchiveRouteImport
      parentRoute: typeof AuthenticatedContactDispatchRoute
    }
    '/_authenticated/accounts/$accountNumber': {
      id: '/_authenticated/accounts/$accountNumber'
      path: '/$accountNumber'
      fullPath: '/accounts/$accountNumber'
      preLoaderRoute: typeof AuthenticatedAccountsAccountNumberRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/freshdesk-tickets/$ticketId/work': {
      id: '/_authenticated/freshdesk-tickets/$ticketId/work'
      path: '/$ticketId/work'
      fullPath: '/freshdesk-tickets/$ticketId/work'
      preLoaderRoute: typeof AuthenticatedFreshdeskTicketsTicketIdWorkRouteImport
      parentRoute: typeof AuthenticatedFreshdeskTicketsRoute
    }
    '/_authenticated/contact-dispatch/$sessionId/work': {
      id: '/_authenticated/contact-dispatch/$sessionId/work'
      path: '/$sessionId/work'
      fullPath: '/contact-dispatch/$sessionId/work'
      preLoaderRoute: typeof AuthenticatedContactDispatchSessionIdWorkRouteImport
      parentRoute: typeof AuthenticatedContactDispatchRoute
    }
    '/_authenticated/additional-work/$workId/work': {
      id: '/_authenticated/additional-work/$workId/work'
      path: '/$workId/work'
      fullPath: '/additional-work/$workId/work'
      preLoaderRoute: typeof AuthenticatedAdditionalWorkWorkIdWorkRouteImport
      parentRoute: typeof AuthenticatedAdditionalWorkRoute
    }
  }
}

interface AuthenticatedAccountsRouteChildren {
  AuthenticatedAccountsAccountNumberRoute: typeof AuthenticatedAccountsAccountNumberRoute
}

const AuthenticatedAccountsRouteChildren: AuthenticatedAccountsRouteChildren = {
  AuthenticatedAccountsAccountNumberRoute:
    AuthenticatedAccountsAccountNumberRoute,
}

const AuthenticatedAccountsRouteWithChildren =
  AuthenticatedAccountsRoute._addFileChildren(
    AuthenticatedAccountsRouteChildren,
  )

interface AuthenticatedAdditionalWorkRouteChildren {
  AuthenticatedAdditionalWorkIndexRoute: typeof AuthenticatedAdditionalWorkIndexRoute
  AuthenticatedAdditionalWorkWorkIdWorkRoute: typeof AuthenticatedAdditionalWorkWorkIdWorkRoute
}

const AuthenticatedAdditionalWorkRouteChildren: AuthenticatedAdditionalWorkRouteChildren =
  {
    AuthenticatedAdditionalWorkIndexRoute:
      AuthenticatedAdditionalWorkIndexRoute,
    AuthenticatedAdditionalWorkWorkIdWorkRoute:
      AuthenticatedAdditionalWorkWorkIdWorkRoute,
  }

const AuthenticatedAdditionalWorkRouteWithChildren =
  AuthenticatedAdditionalWorkRoute._addFileChildren(
    AuthenticatedAdditionalWorkRouteChildren,
  )

interface AuthenticatedContactDispatchRouteChildren {
  AuthenticatedContactDispatchArchiveRoute: typeof AuthenticatedContactDispatchArchiveRoute
  AuthenticatedContactDispatchSessionIdWorkRoute: typeof AuthenticatedContactDispatchSessionIdWorkRoute
}

const AuthenticatedContactDispatchRouteChildren: AuthenticatedContactDispatchRouteChildren =
  {
    AuthenticatedContactDispatchArchiveRoute:
      AuthenticatedContactDispatchArchiveRoute,
    AuthenticatedContactDispatchSessionIdWorkRoute:
      AuthenticatedContactDispatchSessionIdWorkRoute,
  }

const AuthenticatedContactDispatchRouteWithChildren =
  AuthenticatedContactDispatchRoute._addFileChildren(
    AuthenticatedContactDispatchRouteChildren,
  )

interface AuthenticatedFreshdeskTicketsRouteChildren {
  AuthenticatedFreshdeskTicketsTicketIdWorkRoute: typeof AuthenticatedFreshdeskTicketsTicketIdWorkRoute
}

const AuthenticatedFreshdeskTicketsRouteChildren: AuthenticatedFreshdeskTicketsRouteChildren =
  {
    AuthenticatedFreshdeskTicketsTicketIdWorkRoute:
      AuthenticatedFreshdeskTicketsTicketIdWorkRoute,
  }

const AuthenticatedFreshdeskTicketsRouteWithChildren =
  AuthenticatedFreshdeskTicketsRoute._addFileChildren(
    AuthenticatedFreshdeskTicketsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRouteWithChildren
  AuthenticatedAdditionalWorkRoute: typeof AuthenticatedAdditionalWorkRouteWithChildren
  AuthenticatedAssignedToMeRoute: typeof AuthenticatedAssignedToMeRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedCompletedWorkRoute: typeof AuthenticatedCompletedWorkRoute
  AuthenticatedConstellationsRoute: typeof AuthenticatedConstellationsRoute
  AuthenticatedContactDispatchRoute: typeof AuthenticatedContactDispatchRouteWithChildren
  AuthenticatedFreshdeskIntelligenceRoute: typeof AuthenticatedFreshdeskIntelligenceRoute
  AuthenticatedFreshdeskTicketsRoute: typeof AuthenticatedFreshdeskTicketsRouteWithChildren
  AuthenticatedKnowledgeVaultRoute: typeof AuthenticatedKnowledgeVaultRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRouteWithChildren,
  AuthenticatedAdditionalWorkRoute:
    AuthenticatedAdditionalWorkRouteWithChildren,
  AuthenticatedAssignedToMeRoute: AuthenticatedAssignedToMeRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedCompletedWorkRoute: AuthenticatedCompletedWorkRoute,
  AuthenticatedConstellationsRoute: AuthenticatedConstellationsRoute,
  AuthenticatedContactDispatchRoute:
    AuthenticatedContactDispatchRouteWithChildren,
  AuthenticatedFreshdeskIntelligenceRoute:
    AuthenticatedFreshdeskIntelligenceRoute,
  AuthenticatedFreshdeskTicketsRoute:
    AuthenticatedFreshdeskTicketsRouteWithChildren,
  AuthenticatedKnowledgeVaultRoute: AuthenticatedKnowledgeVaultRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
