/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as FreshdeskTicketsRouteImport } from './routes/freshdesk-tickets'
import { Route as ContactDispatchRouteImport } from './routes/contact-dispatch'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdditionalWorkRouteImport } from './routes/additional-work'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsAccountNumberRouteImport } from './routes/accounts.$accountNumber'
import { Route as FreshdeskTicketsTicketIdWorkRouteImport } from './routes/freshdesk-tickets.$ticketId.work'
import { Route as ContactDispatchSessionIdWorkRouteImport } from './routes/contact-dispatch.$sessionId.work'
import { Route as AdditionalWorkWorkIdWorkRouteImport } from './routes/additional-work.$workId.work'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshdeskTicketsRoute = FreshdeskTicketsRouteImport.update({
  id: '/freshdesk-tickets',
  path: '/freshdesk-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactDispatchRoute = ContactDispatchRouteImport.update({
  id: '/contact-dispatch',
  path: '/contact-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditionalWorkRoute = AdditionalWorkRouteImport.update({
  id: '/additional-work',
  path: '/additional-work',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountNumberRoute = AccountsAccountNumberRouteImport.update({
  id: '/$accountNumber',
  path: '/$accountNumber',
  getParentRoute: () => AccountsRoute,
} as any)
const FreshdeskTicketsTicketIdWorkRoute =
  FreshdeskTicketsTicketIdWorkRouteImport.update({
    id: '/$ticketId/work',
    path: '/$ticketId/work',
    getParentRoute: () => FreshdeskTicketsRoute,
  } as any)
const ContactDispatchSessionIdWorkRoute =
  ContactDispatchSessionIdWorkRouteImport.update({
    id: '/$sessionId/work',
    path: '/$sessionId/work',
    getParentRoute: () => ContactDispatchRoute,
  } as any)
const AdditionalWorkWorkIdWorkRoute =
  AdditionalWorkWorkIdWorkRouteImport.update({
    id: '/$workId/work',
    path: '/$workId/work',
    getParentRoute: () => AdditionalWorkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/additional-work': typeof AdditionalWorkRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact-dispatch': typeof ContactDispatchRouteWithChildren
  '/freshdesk-tickets': typeof FreshdeskTicketsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountNumber': typeof AccountsAccountNumberRoute
  '/additional-work/$workId/work': typeof AdditionalWorkWorkIdWorkRoute
  '/contact-dispatch/$sessionId/work': typeof ContactDispatchSessionIdWorkRoute
  '/freshdesk-tickets/$ticketId/work': typeof FreshdeskTicketsTicketIdWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/additional-work': typeof AdditionalWorkRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact-dispatch': typeof ContactDispatchRouteWithChildren
  '/freshdesk-tickets': typeof FreshdeskTicketsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountNumber': typeof AccountsAccountNumberRoute
  '/additional-work/$workId/work': typeof AdditionalWorkWorkIdWorkRoute
  '/contact-dispatch/$sessionId/work': typeof ContactDispatchSessionIdWorkRoute
  '/freshdesk-tickets/$ticketId/work': typeof FreshdeskTicketsTicketIdWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/additional-work': typeof AdditionalWorkRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact-dispatch': typeof ContactDispatchRouteWithChildren
  '/freshdesk-tickets': typeof FreshdeskTicketsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountNumber': typeof AccountsAccountNumberRoute
  '/additional-work/$workId/work': typeof AdditionalWorkWorkIdWorkRoute
  '/contact-dispatch/$sessionId/work': typeof ContactDispatchSessionIdWorkRoute
  '/freshdesk-tickets/$ticketId/work': typeof FreshdeskTicketsTicketIdWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/accounts'
    | '/additional-work'
    | '/auth'
    | '/contact-dispatch'
    | '/freshdesk-tickets'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/accounts/$accountNumber'
    | '/additional-work/$workId/work'
    | '/contact-dispatch/$sessionId/work'
    | '/freshdesk-tickets/$ticketId/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/accounts'
    | '/additional-work'
    | '/auth'
    | '/contact-dispatch'
    | '/freshdesk-tickets'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/accounts/$accountNumber'
    | '/additional-work/$workId/work'
    | '/contact-dispatch/$sessionId/work'
    | '/freshdesk-tickets/$ticketId/work'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/accounts'
    | '/additional-work'
    | '/auth'
    | '/contact-dispatch'
    | '/freshdesk-tickets'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/accounts/$accountNumber'
    | '/additional-work/$workId/work'
    | '/contact-dispatch/$sessionId/work'
    | '/freshdesk-tickets/$ticketId/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AdditionalWorkRoute: typeof AdditionalWorkRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactDispatchRoute: typeof ContactDispatchRouteWithChildren
  FreshdeskTicketsRoute: typeof FreshdeskTicketsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freshdesk-tickets': {
      id: '/freshdesk-tickets'
      path: '/freshdesk-tickets'
      fullPath: '/freshdesk-tickets'
      preLoaderRoute: typeof FreshdeskTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-dispatch': {
      id: '/contact-dispatch'
      path: '/contact-dispatch'
      fullPath: '/contact-dispatch'
      preLoaderRoute: typeof ContactDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/additional-work': {
      id: '/additional-work'
      path: '/additional-work'
      fullPath: '/additional-work'
      preLoaderRoute: typeof AdditionalWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountNumber': {
      id: '/accounts/$accountNumber'
      path: '/$accountNumber'
      fullPath: '/accounts/$accountNumber'
      preLoaderRoute: typeof AccountsAccountNumberRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/freshdesk-tickets/$ticketId/work': {
      id: '/freshdesk-tickets/$ticketId/work'
      path: '/$ticketId/work'
      fullPath: '/freshdesk-tickets/$ticketId/work'
      preLoaderRoute: typeof FreshdeskTicketsTicketIdWorkRouteImport
      parentRoute: typeof FreshdeskTicketsRoute
    }
    '/contact-dispatch/$sessionId/work': {
      id: '/contact-dispatch/$sessionId/work'
      path: '/$sessionId/work'
      fullPath: '/contact-dispatch/$sessionId/work'
      preLoaderRoute: typeof ContactDispatchSessionIdWorkRouteImport
      parentRoute: typeof ContactDispatchRoute
    }
    '/additional-work/$workId/work': {
      id: '/additional-work/$workId/work'
      path: '/$workId/work'
      fullPath: '/additional-work/$workId/work'
      preLoaderRoute: typeof AdditionalWorkWorkIdWorkRouteImport
      parentRoute: typeof AdditionalWorkRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsAccountNumberRoute: typeof AccountsAccountNumberRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsAccountNumberRoute: AccountsAccountNumberRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface AdditionalWorkRouteChildren {
  AdditionalWorkWorkIdWorkRoute: typeof AdditionalWorkWorkIdWorkRoute
}

const AdditionalWorkRouteChildren: AdditionalWorkRouteChildren = {
  AdditionalWorkWorkIdWorkRoute: AdditionalWorkWorkIdWorkRoute,
}

const AdditionalWorkRouteWithChildren = AdditionalWorkRoute._addFileChildren(
  AdditionalWorkRouteChildren,
)

interface ContactDispatchRouteChildren {
  ContactDispatchSessionIdWorkRoute: typeof ContactDispatchSessionIdWorkRoute
}

const ContactDispatchRouteChildren: ContactDispatchRouteChildren = {
  ContactDispatchSessionIdWorkRoute: ContactDispatchSessionIdWorkRoute,
}

const ContactDispatchRouteWithChildren = ContactDispatchRoute._addFileChildren(
  ContactDispatchRouteChildren,
)

interface FreshdeskTicketsRouteChildren {
  FreshdeskTicketsTicketIdWorkRoute: typeof FreshdeskTicketsTicketIdWorkRoute
}

const FreshdeskTicketsRouteChildren: FreshdeskTicketsRouteChildren = {
  FreshdeskTicketsTicketIdWorkRoute: FreshdeskTicketsTicketIdWorkRoute,
}

const FreshdeskTicketsRouteWithChildren =
  FreshdeskTicketsRoute._addFileChildren(FreshdeskTicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AdditionalWorkRoute: AdditionalWorkRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactDispatchRoute: ContactDispatchRouteWithChildren,
  FreshdeskTicketsRoute: FreshdeskTicketsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
